import {
  Brain,
  Zap,
  BookOpen,
  Target,
  Calculator,
  PenTool,
  Volume,
  Sparkles,
  Waves,
  Sun,
} from 'lucide-react';
import { NeuroOption } from 'types/neuro';

export const NEURO_OPTIONS: NeuroOption[] = [
  {
    id: 'autism',
    name: '🧩 Autism',
    description: 'Visual schedules, routine support, sensory-friendly',
    longDescription: 'Structured learning with clear routines and visual guides',
    colorClass: 'bg-blue-50 text-blue-900 border-blue-300 hover:bg-blue-100',
    icon: Brain,
    theme: { primary: 'blue', secondary: 'indigo', background: 'bg-blue-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-blue-500' },
    learningStyle: 'Visual & Structured',
  },
  {
    id: 'adhd',
    name: '🦋 ADHD',
    description: 'Focus timers, movement breaks, gamified',
    longDescription: 'Energetic learning with built-in movement and rewards',
    colorClass: 'bg-yellow-50 text-yellow-900 border-yellow-300 hover:bg-yellow-100',
    icon: Zap,
    theme: { primary: 'yellow', secondary: 'orange', background: 'bg-yellow-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-yellow-500' },
    learningStyle: 'Dynamic & Gamified',
  },
  {
    id: 'dyslexia',
    name: '📖 Dyslexia',
    description: 'OpenDyslexic font, colored overlays, audio',
    longDescription: 'Text-to-speech, special fonts, and reading support',
    colorClass: 'bg-purple-50 text-purple-900 border-purple-300 hover:bg-purple-100',
    icon: BookOpen,
    theme: { primary: 'purple', secondary: 'violet', background: 'bg-purple-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-purple-500' },
    learningStyle: 'Multi-sensory Reading',
  },
  {
    id: 'dysgraphia',
    name: '✍️ Dysgraphia',
    description: 'Speech-to-text, writing guides, motor support',
    longDescription: 'Express ideas through voice, drawing, or assisted writing',
    colorClass: 'bg-green-50 text-green-900 border-green-300 hover:bg-green-100',
    icon: PenTool,
    theme: { primary: 'green', secondary: 'emerald', background: 'bg-green-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-green-500' },
    learningStyle: 'Voice & Motor-Friendly',
  },
  {
    id: 'dyscalculia',
    name: '🧮 Dyscalculia',
    description: 'Visual math tools, number patterns',
    longDescription: 'Math made visual with patterns and real-world examples',
    colorClass: 'bg-red-50 text-red-900 border-red-300 hover:bg-red-100',
    icon: Calculator,
    theme: { primary: 'red', secondary: 'rose', background: 'bg-red-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-red-500' },
    learningStyle: 'Visual Mathematics',
  },
  {
    id: 'dyspraxia',
    name: '🤸 Dyspraxia',
    description: 'Coordination games, motor planning',
    longDescription: 'Movement-friendly activities and coordination support',
    colorClass: 'bg-teal-50 text-teal-900 border-teal-300 hover:bg-teal-100',
    icon: Target,
    theme: { primary: 'teal', secondary: 'cyan', background: 'bg-teal-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-teal-500' },
    learningStyle: 'Movement & Coordination',
  },
  {
    id: 'spd',
    name: '🎵 SPD (Sensory)',
    description: 'Calming sounds, brightness control',
    longDescription: 'Sensory regulation tools and calming environments',
    colorClass: 'bg-pink-50 text-pink-900 border-pink-300 hover:bg-pink-100',
    icon: Waves,
    theme: { primary: 'pink', secondary: 'rose', background: 'bg-pink-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-pink-500' },
    learningStyle: 'Sensory-Regulated',
  },
  {
    id: 'auditory',
    name: '👂 Auditory Processing',
    description: 'Clear speech, visual reinforcements',
    longDescription: 'Enhanced audio with visual cues and captions',
    colorClass: 'bg-indigo-50 text-indigo-900 border-indigo-300 hover:bg-indigo-100',
    icon: Volume,
    theme: { primary: 'indigo', secondary: 'blue', background: 'bg-indigo-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-indigo-500' },
    learningStyle: 'Visual + Audio Support',
  },
  {
    id: 'visual-stress',
    name: '👁️ Visual Stress',
    description: 'Low contrast, font scaling, color themes',
    longDescription: 'Comfortable viewing with adjustable visual settings',
    colorClass: 'bg-amber-50 text-amber-900 border-amber-300 hover:bg-amber-100',
    icon: Sun,
    theme: { primary: 'amber', secondary: 'yellow', background: 'bg-amber-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-amber-500' },
    learningStyle: 'Visual Comfort',
  },
  {
    id: 'tourettes',
    name: "💫 Tourette's",
    description: 'Tic-friendly, no time pressure',
    longDescription: 'Flexible timing and accepting interface',
    colorClass: 'bg-violet-50 text-violet-900 border-violet-300 hover:bg-violet-100',
    icon: Sparkles,
    theme: { primary: 'violet', secondary: 'purple', background: 'bg-violet-50', cardBg: 'bg-white/90', accent: 'border-l-4 border-violet-500' },
    learningStyle: 'Flexible & Accepting',
  },
];

export const NEURO_OPTION_MAP = Object.fromEntries(
  NEURO_OPTIONS.map((option) => [option.id, option]),
) as Record<string, NeuroOption>;
