/** Central route paths — align with /app/* as features mature */
export const ROUTES = {
  HOME: '/',
  NEURO_SELECTOR: '/neuro-selector',
  COMPANION_ONBOARDING: '/companion-onboarding',
  COMPANION_BUDDY: '/companion-buddy',
  LOGIN: '/login',
  GUEST_ENTRY: '/guest',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  CHILD_DASHBOARD: '/dashboard',
  AUTISM_SPACE: '/autism-space',
  CHILD_SETTINGS: '/settings',
  WRITING_PAD: '/writing-pad',
  PRONUNCIATION_BUDDY: '/pronunciation-buddy',
  PARENT_HUB: '/parent-hub',
  MUSIC: '/music',
  TEACHER_LOGIN: '/teacher',
  TEACHER_DASHBOARD: '/teacher/dashboard',
  TEACHER_CLASSES: '/teacher/classes',
  TEACHER_STUDENTS: '/teacher/students',
  TEACHER_ASSIGNMENTS: '/teacher/assignments',
  TEACHER_SIGNALS: '/teacher/signals',
  TEACHER_MESSAGES: '/teacher/messages',
  TEACHER_REPORTS: '/teacher/reports',
  TEACHER_SETTINGS: '/teacher/settings',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_AUDIT: '/admin/audit',
  ADMIN_SETTINGS: '/admin/settings',
} as const;
